"""Fix QSS labels by applying NAICS-based category name mapping."""
import json

QSS_CATEGORIES = {
    "000000A": "All Selected Service Industries",
    "22T": "Utilities",
    "2211T": "Electric Power",
    "22121T": "Natural Gas Distribution",
    "2213T": "Water, Sewage and Other Systems",
    "481T": "Air Transportation",
    "4831T": "Deep Sea and Great Lakes Water Transportation",
    "483T": "Water Transportation",
    "48412T": "Long-Distance General Freight Trucking",
    "4841T": "General Freight Trucking",
    "4842T": "Specialized Freight Trucking",
    "4849YT": "Other Freight Trucking",
    "484T": "Truck Transportation",
    "485T": "Transit and Ground Passenger Transportation",
    "486T": "Pipeline Transportation",
    "487T": "Scenic and Sightseeing Transportation",
    "488T": "Support Activities for Transportation",
    "492T": "Couriers and Messengers",
    "51111T": "Newspaper Publishers",
    "51112T": "Periodical Publishers",
    "5111T": "Newspaper, Periodical, Book, and Directory Publishers",
    "5111XT": "Book and Other Publishers",
    "5112T": "Software Publishers",
    "511T": "Publishing Industries",
    "512T": "Motion Picture and Sound Recording",
    "5151T": "Radio and Television Broadcasting",
    "5152T": "Cable and Other Subscription Programming",
    "515T": "Broadcasting (except Internet)",
    "517311T": "Wired Telecommunications Carriers",
    "517312T": "Wireless Telecommunications Carriers",
    "518T": "Data Processing and Hosting",
    "519T": "Other Information Services",
    "51T": "Information",
    "5221T": "Depository Credit Intermediation",
    "5223T": "Activities Related to Credit Intermediation",
    "522T": "Credit Intermediation and Related Activities",
    "5311T": "Lessors of Real Estate",
    "5312T": "Offices of Real Estate Agents and Brokers",
    "5313T": "Activities Related to Real Estate",
    "531T": "Real Estate",
    "53211T": "Passenger Car Rental and Leasing",
    "53212T": "Truck, Utility Trailer, and RV Rental",
    "5321T": "Automotive Equipment Rental and Leasing",
    "5324T": "Commercial and Industrial Equipment Rental",
    "532T": "Rental and Leasing Services",
    "533T": "Lessors of Nonfinancial Intangible Assets",
    "53T": "Real Estate and Rental and Leasing",
    "5411T": "Legal Services",
    "5412T": "Accounting and Bookkeeping Services",
    "54133T": "Engineering Services",
    "5413T": "Architectural and Engineering Services",
    "5415T": "Computer Systems Design",
    "5416T": "Management and Technical Consulting",
    "5417T": "Scientific Research and Development",
    "5418T": "Advertising and Public Relations",
    "5419T": "Other Professional and Technical Services",
    "54T": "Professional, Scientific, and Technical Services",
    "5613T": "Employment Services",
    "5615T": "Travel Arrangement and Reservation",
    "561T": "Administrative and Support Services",
    "561YT": "Other Administrative and Support Services",
    "562T": "Waste Management and Remediation",
    "56T": "Administrative, Support, and Waste Management",
    "6116A": "Other Schools and Instruction",
    "61171A": "Educational Support Services",
    "61A": "Educational Services",
    "6211T": "Offices of Physicians",
    "6212T": "Offices of Dentists",
    "6213T": "Offices of Other Health Practitioners",
    "6214A": "Outpatient Care Centers",
    "6214E": "Outpatient Care Centers (Tax-Exempt)",
    "6214T": "Outpatient Care Centers (Total)",
    "6215T": "Medical and Diagnostic Laboratories",
    "6216A": "Home Health Care Services",
    "6216E": "Home Health Care Services (Tax-Exempt)",
    "6216T": "Home Health Care Services (Total)",
    "6219A": "Other Ambulatory Health Care Services",
    "6219E": "Other Ambulatory Health Care (Tax-Exempt)",
    "6219T": "Other Ambulatory Health Care (Total)",
    "621A": "Ambulatory Health Care Services",
    "621E": "Ambulatory Health Care Services (Tax-Exempt)",
    "621T": "Ambulatory Health Care Services (Total)",
    "6221A": "General Medical and Surgical Hospitals",
    "6221E": "General Medical and Surgical Hospitals (Tax-Exempt)",
    "6221T": "General Medical and Surgical Hospitals (Total)",
    "6222A": "Psychiatric and Substance Abuse Hospitals",
    "6222E": "Psychiatric and Substance Abuse Hospitals (Tax-Exempt)",
    "6222T": "Psychiatric and Substance Abuse Hospitals (Total)",
    "6223A": "Specialty Hospitals",
    "6223E": "Specialty Hospitals (Tax-Exempt)",
    "622A": "Hospitals",
    "622E": "Hospitals (Tax-Exempt)",
    "622T": "Hospitals (Total)",
    "623A": "Nursing and Residential Care Facilities",
    "623E": "Nursing and Residential Care (Tax-Exempt)",
    "623T": "Nursing and Residential Care (Total)",
    "6241A": "Individual and Family Services",
    "6242A": "Community Food and Housing Services",
    "6243A": "Vocational Rehabilitation Services",
    "6244A": "Child Day Care Services",
    "6244E": "Child Day Care Services (Tax-Exempt)",
    "6244T": "Child Day Care Services (Total)",
    "624A": "Social Assistance",
    "624E": "Social Assistance (Tax-Exempt)",
    "62A": "Health Care and Social Assistance",
    "62E": "Health Care and Social Assistance (Tax-Exempt)",
    "7111A": "Performing Arts Companies",
    "7111E": "Performing Arts Companies (Tax-Exempt)",
    "7111T": "Performing Arts Companies (Total)",
    "7112T": "Spectator Sports",
    "7113A": "Promoters of Performing Arts and Sports",
    "7113T": "Promoters of Performing Arts and Sports (Total)",
    "71141T": "Agents and Managers for Artists",
    "71151T": "Independent Artists, Writers, Performers",
    "711A": "Performing Arts and Spectator Sports",
    "711T": "Performing Arts and Spectator Sports (Total)",
    "712A": "Museums and Historical Sites",
    "712E": "Museums and Historical Sites (Tax-Exempt)",
    "7131T": "Amusement Parks and Arcades",
    "7132T": "Gambling Industries",
    "7139A": "Other Amusement and Recreation",
    "7139E": "Other Amusement and Recreation (Tax-Exempt)",
    "7139T": "Other Amusement and Recreation (Total)",
    "713A": "Amusement, Gambling, and Recreation",
    "713E": "Amusement, Gambling, and Recreation (Tax-Exempt)",
    "713T": "Amusement, Gambling, and Recreation (Total)",
    "71A": "Arts, Entertainment, and Recreation",
    "71E": "Arts, Entertainment, and Recreation (Tax-Exempt)",
    "71T": "Arts, Entertainment, and Recreation (Total)",
    "7211T": "Traveler Accommodation",
    "7212T": "RV Parks and Recreational Camps",
    "7213T": "Rooming and Boarding Houses",
    "721T": "Accommodation",
    "8111T": "Automotive Repair and Maintenance",
    "8114T": "Personal and Household Goods Repair",
    "811T": "Repair and Maintenance",
    "8121T": "Personal Care Services",
    "8123T": "Dry-cleaning and Laundry Services",
    "8129T": "Other Personal Services",
    "812T": "Personal and Laundry Services",
    "813E": "Religious, Civic, and Professional Organizations",
    "81A": "Other Services",
}

QSS_DTYPES = {
    "QREV": "Quarterly Revenue",
    "PQREV": "% Change Quarterly Revenue",
    "QEXP": "Quarterly Expenses",
    "PQEXP": "% Change Quarterly Expenses",
}

data = json.load(open(r"C:\projects\newcocharts\data\json\qss\qss.json"))
unmapped = set()
for s in data["series"]:
    cat, dtype = s["id"].rsplit("_", 1)
    cat_name = QSS_CATEGORIES.get(cat, None)
    if cat_name is None:
        unmapped.add(cat)
        cat_name = cat
    dtype_name = QSS_DTYPES.get(dtype, dtype)
    s["name"] = f"{cat_name} - {dtype_name}"

with open(r"C:\projects\newcocharts\data\json\qss\qss.json", "w") as f:
    json.dump(data, f)

print(f"QSS: {len(data['series'])} series updated")
if unmapped:
    print(f"  Unmapped categories: {sorted(unmapped)}")
for s in data["series"][:8]:
    print(f"  {s['name']}")
